spring.application.name=hospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=yugshah91

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-location=classpath:sata.sql

#security config
spring.security.user.name=yug
spring.security.user.password=1234
jwt.secretKey=afhvberikvjmscvd54roeaowe425odcv35tr2mwoeiororeifowrbgtfrsrbgfv35vaswef
